### ISSUE TITLE
handling INI file without sections

### ISSUE THREAD

**Issue by rickhelmus** [dvdscripter/ini#3]
Hello,

Thanks for this nice and straightforward package!

I'm wanting to parse an INI file generated by another tool and store any modifications afterwards. These files do not contain any sections, which `read.ini` (and I guess `write.ini`) don't really like. 

The error in question is
```
Error in ini::read.ini("...") : 
  object 'lastSection' not found
```
Perhaps `lastSection` could be initialized with a default dummy value?

(I guess for now a workaround would be to manually inject a dummy section prior to parsing the file and do the writing with another function.)

Regards,
Rick

**Comment by dvdscripter** [comment]
Hi @rickhelmus,

ini file format has no formal standard to follow. I'm using the same pattern windows use with https://docs.microsoft.com/pt-br/windows/win32/api/winbase/nf-winbase-getprivateprofilestring?redirectedfrom=MSDN

Also IIRC this package had 5/6 reverse dependencies and changing behavior might brake other packages inside CRAN.

I recommend you to use [configr](https://cran.r-project.org/web/packages/configr/index.html) and try TOML file format (keys without section).

Thank you

**Comment by rickhelmus** [comment]
Excellent, thanks for the quick reply and the pointer to `configr`! Will check it out.
